- src/lib/pipeline/ReorderBuffer.cc
When SimEng flushes an instruction that sets multiple destinations as
same register, the rewinding of register renaming fails.
This is because the order of applying rewinding by historyTable_ is
in the wrong way.
Ultimately, it keeps the wrong physical register (which was freed) in mappingTable_.
Therefore, the order of calling rewind() was reversed to have the correct
order of updating mappingTable_ with historyTable_.
> Reverse register rename rewinding order on flush

- src/lib/arch/aarch64/Instruction_address.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- test/regression/aarch64/instructions/load.cc
- test/regression/aarch64/instructions/neon.cc
- test/regression/aarch64/instructions/store.cc
This branch adds more instructions to support OpenMP enabled minifmm.
Currently, GCC and Armclang compiled fmm.omp-for can be fully executed.
When SimEng runs Armclang compiled version of fmm.omp-for, a bug was found.
It made SimEng to stuck in infinite loop.
To run Armclang version without issues, it will be ideal to merge PR Bug fixes #192 before merging this PR.
> Minifmm support

- src/include/simeng/arch/aarch64/helpers/auxiliaryFunctions.hh
- src/include/simeng/arch/aarch64/helpers/sve.hh
- src/lib/arch/aarch64/InstructionMetadata.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- test/regression/aarch64/instructions/sve.cc
Fixes output error present for miniBUDE when compiled with GCC-10.3.0 targeting armv8.4-a+sve, caused by an incorrect implementation of the FNEG sve instruction. 
Additionally, other SVE instructions were updated to accomodate for optional patterns.
> Fix for sve FNEG (predicated) instruction

- .jenkins/build_arm22.sh
The old armclang20 compiler we were using has an associated license which has now expired. The most recent armclang compilers don't need a compiler so the Isambard support team has installed the armclang22 compiler which we'll now use for our Jenkins CI.
I've added everyone with active or upcoming PRs as reviewers so you're all aware of this. You'll need to rebase `dev` onto your branches to pass the Jenkins armclang build pipeline.
> Updated jenkins armclang build script to use new armclang22 compiler

- CMakeLists.txt
- simeng-fileio-test.txt
- src/include/simeng/arch/aarch64/MicroDecoder.hh
- src/include/simeng/arch/aarch64/helpers/sve.hh
- src/lib/CMakeLists.txt
- src/lib/Instruction.cc
- src/lib/arch/aarch64/InstructionMetadata.cc
- src/lib/arch/aarch64/Instruction_address.cc
- src/lib/arch/aarch64/Instruction_decode.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- src/lib/arch/aarch64/MicroDecoder.cc
This pull request updates SimEng to use the Armv9.2-update branch of the UoB-HPC Capstone Fork. 
Changes to the CMake files have been changed to reflect build changes in the upstream Capstone:next branch.
A pre-upstreamed update to Capstone has been merged into the Armv9.2-update, which adds support for the AArch64 Armv9.2-a ISA (including SVE2 and SME instructions). As such, minor fixes have been made to accomodate changes to instruction enums, aliasing logic, and other changes.
Although the Capstone update allows for additional instructions to be supported by SimEng, this PR does not include any such updates - it only contains changes to work with a new Capstone version.
Instruction enum changes seen in `Instruction_address.cc`, `Instruction_execute.cc` and `Instruction_metadata.cc` …
> Capstone update

- configs/a64fx.yaml
- configs/m1_firestorm.yaml
- configs/tx2.yaml
- src/include/simeng/BranchPredictor.hh
- src/include/simeng/CoreInstance.hh
- src/include/simeng/MemoryInterface.hh
- src/include/simeng/ModelConfig.hh
- src/include/simeng/arch/Architecture.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/include/simeng/models/inorder/Core.hh
- src/include/simeng/pipeline/FetchUnit.hh
- src/include/simeng/pipeline/LoadStoreQueue.hh
- src/lib/CMakeLists.txt
- src/lib/CoreInstance.cc
- src/lib/ModelConfig.cc
- src/lib/models/inorder/Core.cc
- src/lib/models/outoforder/Core.cc
- src/tools/simeng/main.cc
- test/regression/aarch64/AArch64RegressionTest.hh
A new CoreInstance class which creates the core and its associated memory interfaces. `main.cc` now creates an instance of this class and uses it to generate the SimEng simulation objects.
This change was influenced by the need to remove any dependencies SST had on yaml-cpp due to AppleClang having issues linking them. Through this class, the new SST core wrapper can now use the new CoreINstance class to create all SimEng objects without the need to link against the yaml-ccp external project.
> New core creation

- src/lib/kernel/Linux.cc
> Fix memory leak in `Linux::getdents64`

- src/lib/pipeline/DispatchIssueUnit.cc
> Don't const qualify things we'll be moving later.

- test/regression/RegressionTest.hh
> Don't use type punning for `RegressionTest::getMemoryValue`

- src/include/simeng/arch/aarch64/InstructionGroups.hh
- src/include/simeng/arch/riscv/InstructionGroups.hh
This pull request fixes the warning produced due to the name clash of NUM_GROUPS within riscv/InstructionGroups.hh and aarch64/InstructionGroups.hh. Instead of using #define which is resolved during pre-processing, these are changed to constexpr's which conform to namespaces so don't clash and also allows for type checking.
> Fix NUM_GROUPS warning

- configs/a64fx_SME.yaml
- docs/sphinx/user/configuring_simeng.rst
- src/include/simeng/ModelConfig.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/include/simeng/pipeline/DispatchIssueUnit.hh
- src/include/simeng/pipeline/ReorderBuffer.hh
- src/lib/ModelConfig.cc
- src/lib/arch/aarch64/Architecture.cc
- src/lib/arch/aarch64/ExceptionHandler.cc
- src/lib/arch/aarch64/Instruction.cc
- src/lib/arch/aarch64/InstructionMetadata.cc
- src/lib/arch/aarch64/Instruction_address.cc
- src/lib/arch/aarch64/Instruction_decode.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- src/lib/kernel/LinuxProcess.cc
- src/lib/pipeline/DispatchIssueUnit.cc
- src/lib/pipeline/LoadStoreQueue.cc
- src/lib/pipeline/ReorderBuffer.cc
- sst/SimEngCoreWrapper.cc
- test/regression/aarch64/AArch64RegressionTest.hh
- test/regression/aarch64/instructions/float.cc
- test/regression/aarch64/instructions/store.cc
As well as some AArch64 instruction support, the following fixes are implemented : 
- Added example SME core (A64FX with in-core SME support)
- Fixes MIPS calculation in CoreWrapper.cc
- Fixed store instruction group allocation logic for non-SVE instructions
- Corrected SME instruction group allocation in
- Reassign LdAddr iterator after erasing element in LSQ load conflict logic (originally in PR #272)
- Moved optinisations of PR #274 into this PR :
- Refactored the `ReorderBuffer::commitMicroOps` method by using binary search to find the list of uops with the same instruction id. This improves the complexity from O(n) to O(logn)
- Changed the `DispatchIssueUnit::tick` method to use a dynamic array instead of initializing a vector for each method call. This eliminates ~ 14m memory …
> AArch64 Instruction support & minor bug fixes

- .jenkins/build_test_run.sh
- src/include/simeng/OS/SimOS.hh
- src/include/simeng/OS/SyscallHandler.hh
- src/include/simeng/arch/ExceptionHandler.hh
- src/lib/OS/SimOS.cc
- src/lib/OS/SyscallHandler.cc
- src/lib/arch/aarch64/ExceptionHandler.cc
- src/lib/arch/riscv/ExceptionHandler.cc
- src/lib/models/emulation/Core.cc
- src/lib/models/inorder/Core.cc
- src/lib/models/outoforder/Core.cc
- test/unit/OSTest.cc
Implemented the `exit` and `exit_group` syscalls, along with a mechanism to allow a syscall to update the core's status to idle, once the process state returned from the syscall has been applied.
Also includes a minor tweak to the scheduling logic, meaning that if `scheduledProcs_` is empty then a process in `waitingProcs_` can jump ahead.
(Will re-target to `multi-thread-support` branch once the `exceptionHandler-refactor` PR has been merged)
> Exit and Exit_Group syscalls

- configs/DEMO_RISCV.yaml
- configs/a64fx.yaml
- configs/a64fx_SME.yaml
- configs/m1_firestorm.yaml
- configs/tx2.yaml
- src/lib/ModelConfig.cc
- src/lib/OS/Process.cc
- src/lib/arch/aarch64/InstructionMetadata.cc
- src/lib/arch/aarch64/Instruction_address.cc
- src/lib/arch/aarch64/Instruction_decode.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- test/regression/aarch64/instructions/load.cc
Along with the ldaddal instruction being added, the user can now input the environment variables they want to use via the YAML config file, rather than in Process.cc
> Minibude instruction support for openmp

- src/lib/OS/SyscallHandler.cc
- test/regression/aarch64/Syscall.cc
In this PR, the `sysinfo` syscall infrastructure has been introduced. Currently, not all values of the returned `sysinfo` struct (generated by the `sysinfo` syscall) are supported so have been set to zero and left for either future developments or within the lifetime of this PR based on actual usage of the syscall. 
Rather than define the `sysinfo` struct in the `SyscallHandler` header and verbosely assign each `sysinfo` struct entry  to then be added to the statechange one by one, the struct is represented as an array of `uint64_t` values. This allowed for less duplicate code and a smaller code footprint within the `sysinfo` case body. A somewhat detailed comment has been written to explain the mapping/use of this array.
> Added first draft logic and test for the sysinfo syscall

- src/include/simeng/Port.hh
- src/include/simeng/memory/FixedLatencyMemory.hh
- src/include/simeng/memory/MMU.hh
- src/include/simeng/memory/Mem.hh
- src/include/simeng/memory/MemPacket.hh
- src/include/simeng/memory/MemRequests.hh
- src/include/simeng/memory/SimpleMem.hh
- src/lib/arch/aarch64/Instruction.cc
- src/lib/arch/riscv/Instruction.cc
- src/lib/memory/FixedLatencyMemory.cc
- src/lib/memory/MMU.cc
- src/lib/memory/MemPacket.cc
- src/lib/memory/SimpleMem.cc
- src/lib/models/emulation/Core.cc
- src/lib/models/inorder/Core.cc
- src/lib/pipeline/FetchUnit.cc
- src/lib/pipeline/LoadStoreQueue.cc
- test/unit/SimpleMem.cc
- test/unit/pipeline/FetchUnitTest.cc
- test/unit/pipeline/LoadStoreQueueTest.cc
- test/unit/pipeline/ReorderBufferTest.cc
Includes:
- Ports are now shared_ptrs
- Size change of `size` in MemoryAcessTarget
- Variable name change to vaddr in MemoryAccessTarget
- Removed unnecessary moves of unique_ptr to references
- General refactor of functions
> Post MMU/MemInterface merge cleanup

- src/include/simeng/OS/Process.hh
- src/lib/OS/Process.cc
- src/lib/models/emulation/Core.cc
- src/lib/models/inorder/Core.cc
- src/lib/models/outoforder/Core.cc
- test/regression/RegressionTest.cc
- test/unit/OSTest.cc
After the updates made for multi-threading-support and memory-overhaul, the programByteLength definition (used by the fetch unit to determine when to not fetch) had changed to the actual length of the process's region rather than the end of the .data section that it had been before.
This meant that any PC value which exceeded the data section (i.e. via speculated fetches on incorrect branch predictions) would be fetched and processed by the decoder, where in some cases when the address branched to was not properly aligned and as such triggered an unaligned PC exception.
To fix this, the context associated to each process now contains `dataSectionEnd`, which is then used by the fetch unit to determine if a PC is valid before sending a request to memory.
> Unaigned PC exception fix

- src/include/simeng/OS/Process.hh
- src/lib/OS/Process.cc
- src/lib/arch/aarch64/Architecture.cc
- src/lib/arch/riscv/Architecture.cc
- src/lib/models/emulation/Core.cc
- src/lib/models/inorder/Core.cc
- src/lib/models/outoforder/Core.cc
- test/regression/RegressionTest.cc
- test/unit/OSTest.cc
This PR reverts PR #315 as this was a) not an actual full fix of the issue, and b) the functionality that it replaced is better suited to support dynamic linking.
Also contained in this PR is the fix for unaligned PC exceptions, caused by decoded instructions not being allocated a sequenceID or instructionID meaning it was never flushed from the ROB (expected for all unaligned PC exceptions given they should only occur through incorrect speculation).
> Unaligned pc exception fix 2

- src/include/simeng/AlwaysNotTakenPredictor.hh
- src/include/simeng/BranchPredictor.hh
- src/include/simeng/GenericPredictor.hh
- src/include/simeng/Instruction.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/include/simeng/arch/riscv/Instruction.hh
- src/include/simeng/pipeline/ExecuteUnit.hh
- src/include/simeng/pipeline/PipelineBuffer.hh
- src/lib/AlwaysNotTakenPredictor.cc
- src/lib/GenericPredictor.cc
- src/lib/arch/aarch64/Instruction.cc
- src/lib/arch/aarch64/Instruction_decode.cc
- src/lib/arch/riscv/Instruction.cc
- src/lib/arch/riscv/Instruction_decode.cc
- src/lib/models/inorder/Core.cc
- src/lib/pipeline/ExecuteUnit.cc
- src/lib/pipeline/FetchUnit.cc
- test/regression/riscv/CMakeLists.txt
- test/regression/riscv/InorderPipeline.cc
- test/regression/riscv/RISCVRegressionTest.hh
- test/unit/MockBranchPredictor.hh
- test/unit/MockInstruction.hh
This pull request adds:
- Correct tagging of RISC-V multiply and divide instructions
- Renaming of  knownTarget_ to knownOffset_ and fixing the RISC-V assignment to this variable
This pull request fixes:
- With the specific sequence of instructions: branch, multi-cycle instruction, branch, the in-order core would sometimes incorrectly halt. 
This would only happen in the case that each branch instruction set knownTarget_ to a value outside the valid range defined by the program size. This is due to incorrectly setting the variable as the instruction's own address had not been initialised and so was some garbage value different on each run. 
This caused a halt because the first mispredicted branch causes a bubble when the fetch unit halts not knowing what to fetch next. Once executed, a …
> In-order Early Halting Fix

- configs/a64fx_SME.yaml
- src/lib/pipeline/ReorderBuffer.cc
The commitMicroOps function was changed to try and gain an overall speedup. This had the unintended side effect of causing segfaults when running the simeng benchmarks. The speedup of the new solution was compared to the old and there is no noticeable difference.
To prevent segfaults this function is reverted to it's old implementation.
> Revert commitMicroOps Function

- src/include/simeng/MemoryInterface.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/lib/arch/aarch64/Instruction.cc
- src/lib/arch/aarch64/Instruction_address.cc
- src/lib/arch/aarch64/Instruction_execute.cc
All single structure, contiguous vector loads (both NEON and SVE) have been adapted to generate a sigle address rather than one per element.
This change is largely motivated by a lack of accuracy to real hardware when simulating with SimEng-SST. Functionally, the instructions have not been altered.
> Update AArch64 Contiguous NEON/SVE Loads

- src/include/simeng/pipeline/LoadStoreQueue.hh
- src/lib/models/outoforder/Core.cc
- src/lib/pipeline/FetchUnit.cc
- src/lib/pipeline/LoadStoreQueue.cc
- sst/SimEngMemInterface.cc
- test/unit/pipeline/LoadStoreQueueTest.cc
- test/unit/pipeline/ReorderBufferTest.cc
Bug fixes for:
- Use of incorrectly speculated loaded values through forward operand calls
- Continuation of memory accesses to the L1I interface whilst the loop buffer was in use causing  high host memory usage
- Memory leak from SSTSimEng aggregated write request objects
> Various memory centric bug fixes

- CMakeLists.txt
On more recent versions of MacOS, and more specifically with more recent versions of Apple Clang, SST is unable to be compiled due to `unary_function` and `binary_function` types being depricated (since c++11) and now removed from Apple Clang v15. There is a compile flag which re-enabled these types and this has been added to `CMakeLists.txt` if the user is on MacOS.
These functions are only used in SST, and in more recent versions (i.e. SST v13) they have been replaced - so this issue may only be short term if SimEng's SST support is updated to version 13+
> SST compile fix on MacOS

- CMakeLists.txt
- src/include/simeng/Instruction.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/include/simeng/arch/riscv/Instruction.hh
- src/lib/arch/aarch64/Architecture.cc
- src/lib/arch/aarch64/ExceptionHandler.cc
- src/lib/arch/aarch64/Instruction.cc
- src/lib/arch/aarch64/InstructionMetadata.cc
- src/lib/arch/aarch64/Instruction_execute.cc
- src/lib/arch/riscv/Instruction.cc
- test/regression/aarch64/Exception.cc
- test/unit/MockInstruction.hh
This PR for the most part addresses issue #329 - correcting the SVCR and Streaming Mode logic introduced with SME. This is summaried as:
-  If a program is in Streaming Mode and calls SMSTART again, ZA and Vector registers are **not** zeroed out. 
- SVE Vector registers (and their aliases such as NEON and Scalar registers) are only zeroed out when SVCR.SM bit changes
- SME's ZA register is only zeroed out when SVCR.ZA bit changes
- SVCR can now be correctly updated using a regulat `msr svcr, xt` instruction in addition to `smstart`/`smstop`/`msr svcr, #imm`
- More tests surrounding the SVCR logic have been added
Additional to this, logic for the NEON muti-struct store with post index instructions introduced in PR #335 has been corrected via a small change to the metadata to correctly …
> SME SVCR logic fix

- src/include/simeng/RegisterFileSet.hh
- src/include/simeng/arch/aarch64/helpers/sve.hh
- src/lib/arch/aarch64/Instruction_execute.cc
- src/lib/pipeline/RegisterAliasTable.cc
- src/lib/pipeline/ReorderBuffer.cc
- test/regression/RegressionTest.cc
- test/regression/aarch64/instructions/sve.cc
Within this PR, various identified bugs in `dev` are resolved. These include:
- A fix for the AArch64 ST1W instruction when the first operand is of form za.d. The existing `sve_merge_store_data` assumed the vector and memory elements were the same width which is false. `sve_merge_store_data` now takes a secondary typename to describe the width of the memory elements.
- It was possible for a test to fail as the process memory wasn't being cleared between `RUN` calls in the regression test suite. The process memory is now zeroed out before populating it.
- The new Alias NYI exceptions did not consider that their non-renamed operands could be rewound if the instruction was fetched on an incorrectly speculated path and reserved an ROB entry. The `Register` struct now has an extra boolean …
> Register bug fixes

- src/lib/arch/riscv/ExceptionHandler.cc
- src/lib/arch/riscv/Instruction_execute.cc
Closes #359 
This PR fixes issue #359 causing CloverLeaf compiled with GCC 12.2 to produce Inf for all floating point values. At beginning of the program execution `fsflags Ra` is called repeatedly. This is a pseudoinstruction for `csrrw x0, fflags, Ra` which discards the result in the zero register. 
The code in the execution handler blindly updated the first value held in the destination register span without checking if it is valid first which is not the case when the only destination is X0. This caused overwriting of registers incorrectly. A simple check is introduced to fix this.
Also in this PR:
- More accurate dummy value returned for the fsrm instruction
- Removal of unused variables in execute
> Correct CSRRW State Change

- src/lib/config/ModelConfig.cc
- test/regression/aarch64/MicroOperation.cc
- test/regression/aarch64/SmokeTest.cc
- test/regression/aarch64/Syscall.cc
- test/regression/aarch64/SystemRegisters.cc
- test/regression/riscv/LoadStoreQueue.cc
- test/regression/riscv/RISCVRegressionTest.hh
- test/regression/riscv/SmokeTest.cc
- test/regression/riscv/Syscall.cc
This PR applies the restrictions for memory interface types possibly based on the Simulation-Mode in use. It also updates the regression test suite to use a fixed L1D for outoforder tests.
closes #372
> Memory interface type check

- src/include/simeng/arch/aarch64/helpers/neon.hh
- src/include/simeng/arch/aarch64/helpers/sve.hh
- src/lib/arch/aarch64/Instruction_execute.cc
- test/regression/aarch64/instructions/float.cc
- test/unit/aarch64/InstructionTest.cc
This PR aims to fix the issues of differing bit-level values for a NaN value return from a vector divide by 0.
closes #380
> Added fix for returning a consistent nan value from a divide by zero

- src/lib/kernel/LinuxProcess.cc
In this PR, `calloc` has been used instead of `malloc` when allocating memory for newly created ELF process images. This ensures all the memory is zero'ed out as to meet expectations of the initial memory space.
> st1w dirtied memory fix

- src/include/simeng/Instruction.hh
- src/include/simeng/arch/Architecture.hh
- src/include/simeng/arch/aarch64/Architecture.hh
- src/include/simeng/arch/aarch64/Instruction.hh
- src/include/simeng/arch/riscv/Architecture.hh
- src/include/simeng/arch/riscv/Instruction.hh
- src/lib/arch/aarch64/Architecture.cc
- src/lib/arch/riscv/Architecture.cc
- src/lib/arch/riscv/Instruction.cc
- test/unit/MockArchitecture.hh
- test/unit/aarch64/ArchitectureTest.cc
- test/unit/aarch64/InstructionTest.cc
- test/unit/pipeline/FetchUnitTest.cc
- test/unit/riscv/InstructionTest.cc
This PR moves common variables into the base Architecture class, ensures functions in `.cc` and `.hh` are in the same order, and generally makes the classes consistent with the codebase.
Closes Issue #357
> Architecture Class cleanup

- src/lib/config/ModelConfig.cc
Several config options in ModelConfig.cc were being accessed before an existence check was being performed. This PR looks to encapsulate those accessed in existence checks.
> Added conditional existence checks before early config option querying

- src/include/simeng/arch/aarch64/helpers/auxiliaryFunctions.hh
- test/unit/aarch64/AuxiliaryFunctionsTest.cc
This PR addresses the issue that bitfieldManipulate has no bounds checking/restriction enforced by the data type in use.
close #394
> AArch64 bitfieldManipulate bounds checking
